# 1. Wstęp

We wstępie należy krótko opisać:
● temat analizy,
● cel pracy,
● powód wyboru danego zbioru danych.

# 2. Opis zbioru danych

In [27]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

In [28]:
df = pd.read_csv('personality_dataset.csv')

In [29]:
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2837 non-null   float64
 1   Stage_fear                 2827 non-null   str
 2   Social_event_attendance    2838 non-null   float64
 3   Going_outside              2834 non-null   float64
 4   Drained_after_socializing  2848 non-null   str
 5   Friends_circle_size        2823 non-null   float64
 6   Post_frequency             2835 non-null   float64
 7   Personality                2900 non-null   str
dtypes: float64(5), str(3)
memory usage: 181.4 KB

In [31]:
df.describe()

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency
count,2837.000000,2838.000000,2834.000000,2823.000000,2835.000000
mean,4.505816,3.963354,3.000000,6.268863,3.564727
std,3.479192,2.903827,2.247327,4.289693,2.926582
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,2.000000,1.000000,3.000000,1.000000
50%,4.000000,3.000000,3.000000,5.000000,3.000000
75%,8.000000,6.000000,5.000000,10.000000,6.000000
max,11.000000,10.000000,7.000000,15.000000,10.000000

In [32]:
for col in df.select_dtypes(exclude=['number']).columns:
    print(col, ':', df[col].unique())

Stage_fear : <StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str
Drained_after_socializing : <StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str
Personality : <StringArray>
['Extrovert', 'Introvert']
Length: 2, dtype: str

Analizowany zbiór danych 'Extrovert vs. Introvert Behavior Data' pochodzi z platformy [Kaggle](https://www.kaggle.com/datasets/rakeshkapilavai/extrovert-vs-introvert-behavior-data?resource=download&select=personality_dataset.csv).
Dane zostały udostępnione przez
Rakesh Kapilavayi. Informacja o ich pochodzeniu oraz sposobie zebrania bądź wygenerowania nie została udostępniona ani opisana.


Analizowany zbiór składa się z 8 zmienny oraz 2900 obserwacji.
Dane zawierają zbiór cech związanych z codziennymi aktywnościami, wzorami badź odczuciami badanych. Dodatkowo zbiór zawiera informacje o tym jaka jest osobowość osoby - ekstrawertyk bądź introwertyk.

Zmienne w zbiorze to

**Time_spent_Alone**

Zmienna ilościowa wyrażająca ilość godzin spędzonych samotnie przez jednostkę w trakcie dnia. Jest wyrażona w godzinach. Cecha ta wydaje się być istotna w kontekście badanego zbioru. Duże spędzanie czasu w samotności często bywa powiązane z osobowością introwertyczną, jednak należy mieć na uwadzę, że istnieją też inne powody dla których jednostka może spędzać dużo czasu w domu jak na przykład tryb pracy.

**Stage_fear**

Zmienna jakościowa binarna przyjmująca wartości 'Yes'/'No' stwierdzająca czy u badanego występuje strach przed wystąpieniami publicznymi. Pozornie może się wydawać, że jest to częśiej powiązane ze stylem introwertycznym jednak strach przed wystąpieniami jest [rodzajem fobii](https://harmonicvoice.pl/glossofobia-czyli-strach-przed-wystapieniami-publicznymi/), która nie jest jednoznacznie powiązana z tą grupą.


**Social_event_attendance**

Zmienna ilościowa określająca częstość  uczęszczania w wydarzeniach towarzyskich. Jest wyrażona w skali 0-10. Cecha ta wydaje się mieć istotne znaczenie, bowiem inormuje o tym w jaki sposób jednostka spędza swój czas.

**Going_outside**

Zmienna ilościowa określająca częstostość wychodzenia z domu. Jest wyrażona w skali 0-10. Podobnie jak powyższa informuje w jaki sposób badany spędza swój czas. Nie określono jednak jasno jaki charakter mają te wyjścia - czy są związane z obowiązkiem zawodowym, życiem społecznym bądź załatwianiem codziennych sprawunków. Nie wskazano również czy wyjścia były w pojedynke czy w grupie.

**Drained_after_socializing**

Zmienna binarna przyjmująca wartości 'Yes'/'No'. Określa czy jednostka czuje się zmęczona po kontaktach z innymi. Wydaje się być szczególnie ważna, ponieważ bezpośrednio informuje o odczuciach jednostki.

**Friends_circle_size**

Zmienna ilościowa informująca o ilości bliskich znajomych. W przedstawionym problemie wydaje się mieć istotny wpływ. Uważa się, że osoby ekstrawertyczne mają w zwyczaju otaczać się wiekszą grupą znajomych.

**Post_frequency**

Zmienna ilościowa określająca częstotliwość udostępniania postów na social mediach. Jest wyrażona w skali 0-10. Może wydawać się że osoby ekstrawertyczne mają silniejszą chęć dzielenia się swoim życiem.

**Personality**

Zmienna jakościowa przyjmująca wartości 'Extrovert'/'Introvert'. W kontekście tego zbioru jest to głowna cecha, która mogłaby by być zmienną przewidywaną na podstawie pozostałych cech

# 3. Przygotowanie danych

In [33]:
df.isna().mean().round(2)

Time_spent_Alone             0.02
Stage_fear                   0.03
Social_event_attendance      0.02
Going_outside                0.02
Drained_after_socializing    0.02
Friends_circle_size          0.03
Post_frequency               0.02
Personality                  0.00
dtype: float64

In [35]:
df.drop(columns=['Personality']).isna().groupby(df['Personality']).mean().round(2).T

Personality                Extrovert  Introvert
Time_spent_Alone                0.02       0.02
Stage_fear                      0.03       0.02
Social_event_attendance         0.02       0.02
Going_outside                   0.02       0.02
Drained_after_socializing       0.01       0.02
Friends_circle_size             0.03       0.03
Post_frequency                  0.02       0.02

In [9]:
df.describe()

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency
count,2837.000000,2838.000000,2834.000000,2823.000000,2835.000000
mean,4.505816,3.963354,3.000000,6.268863,3.564727
std,3.479192,2.903827,2.247327,4.289693,2.926582
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,2.000000,1.000000,3.000000,1.000000
50%,4.000000,3.000000,3.000000,5.000000,3.000000
75%,8.000000,6.000000,5.000000,10.000000,6.000000
max,11.000000,10.000000,7.000000,15.000000,10.000000

In [14]:
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [16]:
df['Stage_fear'].value_counts(dropna=False)

Stage_fear
No     1417
Yes    1410
NaN      73
Name: count, dtype: int64

In [12]:
df['Drained_after_socializing'].value_counts(dropna=False)

Drained_after_socializing
No     1441
Yes    1407
NaN      52
Name: count, dtype: int64

In [15]:
df['Personality'].value_counts(dropna=False)

Personality
Extrovert    1491
Introvert    1409
Name: count, dtype: int64

In [23]:
def fill_missing_with_median_by_group(df, col, group_col='Personality'):
    df[col] = df.groupby(group_col)[col].transform(lambda x: x.fillna(x.median()))

def fill_missing_with_mode_by_group(df, col, group_col='Personality'):
    df[col] = df.groupby(group_col)[col].transform(
        lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x)
    )

fill_missing_with_median_by_group(df, 'Time_spent_Alone')
fill_missing_with_median_by_group(df, 'Social_event_attendance')
fill_missing_with_median_by_group(df, 'Going_outside')
fill_missing_with_median_by_group(df, 'Friends_circle_size')
fill_missing_with_median_by_group(df, 'Post_frequency')


fill_missing_with_mode_by_group(df, 'Stage_fear')
fill_missing_with_mode_by_group(df, 'Drained_after_socializing')

In [24]:
df.isna().mean().round(2)

Time_spent_Alone             0.0
Stage_fear                   0.0
Social_event_attendance      0.0
Going_outside                0.0
Drained_after_socializing    0.0
Friends_circle_size          0.0
Post_frequency               0.0
Personality                  0.0
dtype: float64

W zbiorze danych nie zidentyfikowany żadnych wartości nietypowych bądź podejrzanych. Dane nie wymagały przekształceń zmiennych. Wszystkie cechy wydają się istotne dla przedstawionego problemu, więc żadna nie została usunięta.

W zbiorze występują braki dla danych. Dla kolumny Time_spent_Alone - 2%, Stage_fear - 3%, Social_event_attendance - 2%, Going_outside - 2%, Drained_after_socializing - 2%,, Friends_circle_size - 3%, Post_frequency - 2%. Dodatkowo sprawdzono i rozkład braków dla obu z typów osobowości jest taki sam co wzkazuje na to że braki nie sa powiązane tylko jedną z grup.

Proces uzupełniania brakujących wartości rozpoczęto od pogrupowania zbioru według kolumny Personality. Dla każdej z grup dla zmiennych jakościowych z brakującą wartością policzono modę, a dla ilościowych medianę. Na tym etapie nie posiadamy jeszcze inormacji o rozkładach zmiennych (zostaną sprawdzone w kolejnych punktach) co czyni użycie mediany metodę bezpieczniejszą odporną na wartości odstające w porównaniu do użycia średniej.

# 4. Statystyki opisowe

Dla wybranych zmiennych ilościowych należy obliczyć i zinterpretować możliwie szeroki
zestaw statystyk opisowych, w szczególności:
● średnią arytmetyczną,
● medianę,
● dominantę,
● minimum i maksimum,
● rozstęp,
● kwartyle,
● rozstęp międzykwartylowy,
● wariancję,
● odchylenie standardowe,
● współczynnik zmienności.
Można również uwzględnić dodatkowe miary, np.:
● skośność,
● kurtozę.

Dla zmiennych jakościowych należy podać:
● liczebności,
● częstości,
● udziały procentowe,
● dominantę.
Uwaga: same obliczenia nie są wystarczające. Każda miara powinna zostać krótko
zinterpretowana w odniesieniu do analizowanych danych.

In [ ]:
num_cols = df.select_dtypes(include=['number']).columns.tolist()
cat_cols = df.select_dtypes(exclude=['number']).columns.tolist()

print('Zmienne ilościowe:', num_cols)
print('Zmienne jakościowe:', cat_cols)

In [ ]:
def quantitative_stats(s):
    mean_ = s.mean()
    median_ = s.median()
    mode_ = s.mode().iloc[0] if not s.mode().empty else np.nan
    min_ = s.min()
    max_ = s.max()
    range_ = max_ - min_
    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    iqr = q3 - q1
    var_ = s.var()
    std_ = s.std()
    cv = (std_ / mean_) * 100 if mean_ != 0 else np.nan
    skew_ = skew(s, bias=False)
    kurt_ = kurtosis(s, bias=False)

    result = pd.Series({
        'średnia': mean_,
        'mediana': median_,
        'dominanta': mode_,
        'minimum': min_,
        'maksimum': max_,
        'rozstęp': range_,
        'Q1': q1,
        'Q3': q3,
        'rozstęp międzykwartylowy': iqr,
        'wariancja': var_,
        'odchylenie standardowe': std_,
        'współczynnik zmienności [%]': cv,
        'skośność': skew_,
        'kurtoza': kurt_
    })

    return result


quant_summary = pd.DataFrame({col: quantitative_stats(df[col]) for col in num_cols}).T
quant_summary

In [ ]:
def qualitative_stats(s):
    counts = s.value_counts()
    freqs = s.value_counts(normalize=True)
    perc = s.value_counts(normalize=True) * 100
    mode_ = s.mode().iloc[0] if not s.mode().empty else np.nan

    summary = pd.DataFrame({
        'liczebność': counts,
        'częstość': freqs,
        'udział procentowy': perc,
        'mode': mode_ 
    })

    return summary



    summary = qualitative_stats(df[col])

qualt_summary = pd.DataFrame.from_dict(
    {col: qualitative_stats(df[col]) for col in cat_cols},
    orient='index'
)

Dla zmiennych jakościowych należy podać:
● liczebności,
● częstości,
● udziały procentowe,
● dominantę.
Uwaga: same obliczenia nie są wystarczające. Każda miara powinna zostać krótko
zinterpretowana w odniesieniu do analizowanych danych.

# 5. Wizualizacja danych

Należy przygotować odpowiednie wykresy dla analizowanych zmiennych. W pracy powinny
pojawić się co najmniej:
● histogram,
● boxplot,
● violin plot,
● scatter plot
● barplot,
● pie chart.
Dla każdej wizualizacji należy:
● nadać tytuł,
● opisać osie,
● dodać krótki komentarz,
● zinterpretować, co przedstawia wykres.
Wykresy powinny być dobrane sensownie do typu zmiennej. Należy pamiętać, że:
● histogram, boxplot i violin plot stosujemy głównie do zmiennych ilościowych,
● barplot i pie chart stosujemy głównie do zmiennych jakościowych.

# 6. Porównanie względem cechy jakościowej

Należy przeprowadzić porównanie wybranej zmiennej ilościowej w grupach wyznaczonych
przez cechę jakościową.
Przykładowo można porównać:
● wiek w zależności od płci,
● cenę w zależności od kategorii produktu,
● wynik egzaminu w zależności od grupy studentów.
W tej części należy:
● przedstawić tabelę statystyk w grupach,
● zaprezentować odpowiedni wykres porównawczy,
● opisać i zinterpretować otrzymane różnice.

# 7. Analiza zależności między zmiennymi

Należy przeanalizować przynajmniej jedną zależność między dwiema zmiennymi. Możliwe
przykłady:
● dwie zmienne ilościowe: wykres rozrzutu, korelacja,
● zmienna ilościowa i jakościowa: porównanie rozkładów między grupami,
● dwie zmienne jakościowe: tabela kontyngencji, wykres słupkowy.
Należy krótko opisać, czy między zmiennymi można zauważyć zależność i jakiego jest ona
rodzaju.

# 8. Wnioski końcowe

W zakończeniu należy podsumować najważniejsze wyniki analizy, w szczególności:
● jakie są typowe wartości analizowanych cech,
● jak duże jest zróżnicowanie danych,
● czy występują obserwacje odstające,
● czy grupy różnią się między sobą,
● jakie zależności udało się zaobserwować.
Wnioski powinny być rzeczowe i wynikać z przedstawionych wcześniej obliczeń i wykresów.